server:
  port: 8080

spring:
  application:
    name: ryver-gateway

eureka:
  client:
    register-with-eureka: false # The gateway should not be registered as a service.
    fetch-registry: true        # The gateway needs the registry to find other services.
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    hostname: ryver-registry

zuul:
  sensitive-headers: Cookie,Set-Cookie
  ribbon:
    eager-load:
      enabled: true
  routes:
    login:
      path: /login
      service-id: ryver-auth
      strip-prefix: false
    customers:
      path: /customers/**
      service-id: ryver-auth
      strip-prefix: false
    fts:
      path: /accounts/**
      service-id: ryver-fts
      strip-prefix: false
    cms:
      path: /contents/**
      service-id: ryver-cms
      strip-prefix: false
    market:
      path: /trades/**
      service-id: ryver-market
      strip-prefix: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

