# RESET
# =====
POST https://ryver.life/reset
# POST http://localhost:8080/reset
Authorization: Basic manager_1 01_manager_01


# UTILITY
# =======
### Check active services
# GET https://ryver.life/services
GET http://localhost:8080/services

### Toggle date utility.
POST https://ryver.life/market/close
# POST http://localhost:8080/market/flip-open/true
Authorization: Basic manager_1 01_manager_01

# {{{
# AUTH SERVICE
# ============

### Generate the JWT for a manager
POST http://localhost:8080/login
Accept: application/json
Authorization: Basic manager_1 01_manager_01

### Get all customers
GET http://localhost:8080/customers
Authorization: Basic manager_1 01_manager_01

### Get all customers without right authorities
GET http://localhost:8080/customers
# Authorization: Basic analyst_1 01_analyst_01

### Create new user
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "full_name":"Mark Tan",
    "nric":"S8291266I",
    "phone":"91251234",
    "address":"27 Jalan Alamak S680234",
    "username":"marktan",
    "password":"password",
    "authorities":"ROLE_USER",
    "active": true
}

### Update a user
# If using manager access, most fields should be updatable
# If using customer access, limited fields should be updatable
PUT http://localhost:8080/customers/4
Content-Type: application/json
# Authorization: Basic manager_1 01_manager_01
Authorization: Basic marktan password

{
    "nric":"S8291265Z",
    "phone":"98199189"
}


# CMS SERVICE
# ===========

### Manager view of CMS - retrieve full list of contents
GET http://localhost:8080/contents/
Accept: application/json
Authorization: Basic manager_1 01_manager_01

### Basic user view of CMS - retrieve full list of contents
GET http://localhost:8080/contents/
Accept: application/json

### Manager approves unapproved content
PUT http://localhost:8080/contents/3
Accept: application/json
Authorization: Basic manager_1 01_manager_01

### Analyst uploads new content
POST http://localhost:8080/contents
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title": "Newss 5G technology for Telcos ",
    "summary": "Stock prices for HubStar and 1M has been rising",
    "content": "Buy HubStar and 1M now!"
}

### Analyst updates unapproved content
PUT http://localhost:8080/contents/6
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title": "News 5G technology for Telcos",
    "summary": "Stock prices for HubStar and 1M has been rising",
    "content": "Buy HubStar and 1M now!"
}

### Analyst updates unapproved content
PUT http://localhost:8080/contents/6
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title": "Apple Inc ETFs",
    "summary": "Stock prices has been rising",
    "content": "Buy Apple Inc ETFs now!",
    "approved": true
}

### Analyst deletes content
DELETE http://localhost:8080/contents/2
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01


# ACCOUNT SERVICE
# ===============

### Open account as manager
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01

{
    "customer_id":4,
    "balance":0.0,
    "available_balance":0.0
}

### View own accounts as user
GET http://localhost:8080/accounts
Accept: application/json
Authorization: Basic marktan password

### View each account as user
GET http://localhost:8080/accounts/1
Accept: application/json
Authorization: Basic marktan password

# }}}

# RECOMMENDATIONS
# ===============

### Get recommendations root
GET http://localhost:8080/contents/recommendations/5
Content-Type: application/json
Authorization: Basic good_user_1 01_user_01
