# AUTH SERVICE
# ============

###
POST http://localhost:8080/login
Accept: application/json
Authorization: Basic manager_1 01_manager_01

###
GET http://localhost:8080/customers
Authorization: Basic manager_1 01_manager_01

###
GET http://localhost:8080/customers
Authorization: Basic analyst_1 01_analyst_01

# CMS SERVICE
# ===========

### Basic user view of CMS - retrieve full list of contents
GET http://localhost:8080/contents/
Accept: application/json

### Manager view of CMS - retrieve full list of contents
GET http://localhost:8080/contents/
Accept: application/json
Authorization: Basic manager_1 01_manager_01

### Analyst uploads new content
POST http://localhost:8080/contents
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title": "Newss 5G technology for Telcos ",
    "summary": "Stock prices for HubStar and 1M has been rising",
    "content": "Buy HubStar and 1M now!"
}

### Analyst updates unapproved content
PUT http://localhost:8080/contents/4
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title": "Newss 5G technology for Telcos ",
    "summary": "Stock prices for HubStar and 1M has been rising",
    "content": "Buy HubStar and 1M now!"
}

### Analyst updates unapproved content
PUT http://localhost:8080/contents/4
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

{
    "title": "Apple Inc ETFs",
    "summary": "Stock prices has been rising",
    "content": "Buy Apple Inc ETFs now!"
}

### Manager approves unapproved content
PUT http://localhost:8080/contents/3
Accept: application/json
Authorization: Basic manager_1 01_manager_01


### Analyst deletes content
DELETE http://localhost:8080/contents/1
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01

